In [45]:
import numpy as np
import time

d=4 # number of dimensions of dataset

# alpha(t) parameters defining grand tour in G2,d
alpha = [1, 2, 3, 4, 5, 6]; 

def getAlpha(d):
    x = [10, 20, 30, 40] #test data point

def getAngles(alpha, d):
    #
    theta = np.zeros((d,d));
    i = 0;
    k = 0;
    #
    while i < d-1:
        j = i + 1;
        #
        while j < d:
            theta[i][j] = alpha[k];
            j += 1;
            k += 1;
        #
        i+= 1;
        
    return theta;

def RotationMatrix(i, j, d, theta):
    R = np.identity(d)
    R[i,i] = np.cos(theta)
    R[i,j] = -1*np.sin(theta)
    R[j,i] = np.sin(theta)
    R[j,j] = np.cos(theta)
    return R

def BetaFn(d, theta):
    beta = RotationMatrix(1, 2, d, theta[1,2])
    i = 1
    j = 2
    for i in range(d):
        for j in range(d):
            if j <= i:
                continue
            if i==1 and j==2:
                continue
            beta = np.matmul(beta, RotationMatrix(i, j, d, theta[i,j]))
    return beta

T = time.time()
theta = getAngles(alpha,d)
T = time.time() - t
print(T)
print(theta)


t = time.time()
B = BetaFn(d,theta)

print(B)

nsteps = 1000
d = 4
transdata = np.zeros((nsteps,d))

for t in range(0,nsteps):
    alpha = [1*t, 2*t, 3*t, 4*t, 5*t, 6*t];
    theta = getAngles(alpha,d)
    B = BetaFn(d,theta)
    a = B.dot(x)
    transdata[t] = a
    
T = time.time() - T
transdatanorm = np.zeros(nsteps)
print(T)
for i in range(0,nsteps):
    transdatanorm[i]=transdata[i][0]**2 + transdata[i][1]**2 + transdata[i][2]**2 + transdata[i][3]**2 

print(transdata)    
print(transdatanorm) 


    

1538117959.989578
[[0. 1. 2. 3.]
 [0. 0. 4. 5.]
 [0. 0. 0. 6.]
 [0. 0. 0. 0.]]
[[ 0.22259496 -0.2691203  -0.24877995 -0.90340151]
 [-0.90787117  0.02391853  0.28270035 -0.30867193]
 [ 0.32604688 -0.16055786  0.92305583 -0.12602593]
 [ 0.14112001  0.94932784  0.07846642 -0.26963832]]
9999.147639036179
[[ 10.          20.          30.          40.        ]
 [-46.75591524 -12.46620775  22.69994962  11.96621669]
 [ -7.54888439  27.1556397   38.0942596  -27.46657901]
 ...
 [-34.01098232  -4.93611107 -36.8751617  -21.42686022]
 [-13.69612279  25.57433492 -28.72465424 -36.51388575]
 [ 15.01646866  27.60987101  32.50083557  30.91757396]]
[3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000.
 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000.
 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000.
 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000.
 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 3000. 300

In [43]:
nsteps = 10000
d = 4
transdata = np.zeros((nsteps,d))

T = time.time()
for t in range(0,nsteps):
    alpha = [1*t,2*t,3*t,4*t,5*t,6*t];
    theta = getAngles(alpha,d)
    B = BetaFn(d,theta)
    a = B.dot(x)
    transdata[t] = a
    
T = time.time() - T
transdatanorm = np.zeros(nsteps)
print(T)
for i in range(0,nsteps):
    transdatanorm[i]=transdata[i][0]**2 + transdata[i][1]**2 + transdata[i][2]**2 + transdata[i][3]**2 

print(transdata)    
print(transdatanorm)

1.215918779373169
[[ 10.          20.          30.          40.        ]
 [-46.75591524 -12.46620775  22.69994962  11.96621669]
 [ -7.54888439  27.1556397   38.0942596  -27.46657901]
 ...
 [ 13.07793065  44.6387982   23.89633759  16.28835397]
 [-19.29096812  29.08881058  40.13615031 -13.06862988]
 [ 23.94280457  36.21908634  32.54756823   7.4549109 ]]
[3000. 3000. 3000. ... 3000. 3000. 3000.]


In [31]:
print(a)
nsteps = 10
d = 4

transdata = np.zeros((nsteps,d))
transdata[0] = a
print(transdata[0])

[-46.75591524 -12.46620775  22.69994962  11.96621669]
[-46.75591524 -12.46620775  22.69994962  11.96621669]


In [32]:
h[0] = a

NameError: name 'h' is not defined

In [40]:
10000/12

833.3333333333334

In [41]:
800/60

13.333333333333334

In [44]:
40*40+30*30+20*20+10*10

3000