In [2]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("/home/dom/Documents/MPhys/TheGrandTour/wine_data.txt", sep="\t");
data = np.array(df);
data = np.delete(data, 0, 0)
data = data.astype(float)
data = np.swapaxes(data,0,1)


classification = data[13]
data = np.delete(data, 13, axis=0)
# Normalizes the data        
for i in range(0, np.shape(data)[0]):
    data[i,:] = (data[i,:] / np.ndarray.max(data[i,:])) * 2 - 1


In [4]:
stepSize = 0.01
nSteps = 10000

def getAlpha(d):
    """
    NEEDS IMPLEMENTATION
    Should produce 1xd(d-1)/2 array of position in grand tour.
    """
    p = d*(d-1)/2     
    primeList = []
    count = 1
    while len(primeList) < p:
        count += 1
        primeBool = False
        for i in range(2, count - 1):
            if count % i == 0:
                primeBool = True
        if primeBool == False:
            irrational = (np.sqrt(count)%1)
            primeList.append(irrational)
            
    primeList = np.asarray(primeList)
    primeList = primeList.dot(stepSize)
    """
    Irrational number generation using exponentials, not being used
    p = int(d*(d-1)/2)
    alpha = np.zeros(p) #alpha(t) parameters defining grand tour in G2,d
    for i in range(0,p):
        alpha[i] = (np.exp(i) % 1) * 2 * np.pi
        
    alpha = alpha.dot(0.001)
    """
    
    
    return primeList


def getAngles(alpha,d):
    """""
    Inputs: 
    alpha = 1xd(d-1)/2 array defining position on grand tour
    d = dimensions of data
    Outputs a dxd array of angles required for the transformation
    """
    theta = np.zeros((d,d));
    i = 0;
    k = 0;
    
    while i < d-1:
        j = i + 1;
        
        while j < d:
            theta[i][j] = alpha[k];
            j += 1;
            k += 1;
    
        i+= 1;
        
    return theta;


def RotationMatrix(i, j, d, theta):
    """
    Inputs:
    i = first indicie of rotating plane
    j = second indicie of rotating plane
    d = dimensions of data
    theta = dxd array of angle of rotation of rotating plane
    Outputs a rotating matrix to rotate plane of ixj plane by theta_ij
    """
    R = np.identity(d)
    R[i,i] = np.cos(theta)
    R[i,j] = -1*np.sin(theta)
    R[j,i] = np.sin(theta)
    R[j,j] = np.cos(theta)
    return R


def BetaFn(d, theta):
    """
    Inputs:
    d = dimensions of data
    theta = dxd array of angle of rotation ixj plane
    Outputs the full matrix transformation for all rotations
    """
    b = RotationMatrix(1, 2, d, theta[1,2])
    i = 1
    j = 2
    for i in range(d):
        for j in range(d):
            if j <= i:
                continue
            if i==1 and j==2:
                continue
            b = np.matmul(b, RotationMatrix(i, j, d, theta[i,j]))
            
    return b


def GrandTour(data, nSteps):
    """
    Inputs:
    data = array of data points, dimensions x npoints
    Outputs a 3D array number of points x t x dimensions, where t
    the time step at that point in the tour
    """

    d = np.shape(data)[0] #dimensions of data
    nPoints = np.shape(data)[1] #number of data points
    tData = np.zeros((nSteps, d, nPoints)) #initialise 3d matrix to store stransforemd data at each timestep
    tBeta = np.zeros((nSteps, d, d))
    Alpha = getAlpha(d)

    
    for t in range(0, nSteps):
        
        
        alpha = Alpha.dot(t)
        theta = getAngles(alpha, d)
        b = BetaFn(d, theta)
        a = np.matmul(b, data)
        tData[t,:,:] = a
        tBeta[t,:,:] = b
        
    return tData, tBeta


tData, tBeta = GrandTour(data, nSteps)


In [5]:
targetData = np.zeros((len(tData[0][0]), 3))
for counter, i in enumerate(classification):
    targetData[counter][int(i-1)] = 1
targetData

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
x = torch.from_numpy(data)
y = torch.from_numpy(targetData)
x = x.float()
y = y.float()
print(x.size())
print(y.size())
#x.transpose_(0, 1)
print(x.size())
print(y.size())

torch.Size([13, 177])
torch.Size([177, 3])
torch.Size([13, 177])
torch.Size([177, 3])


In [7]:
print(x.size())
x.transpose_(0, 1)
x.size()

torch.Size([13, 177])


torch.Size([177, 13])

In [8]:
#print(x[0])
#print(x[1])
print(x.size())
print(y.size())

torch.Size([177, 13])
torch.Size([177, 3])


In [52]:
class Neural_Network(nn.Module):
    
    def __init__(self, ):
        super(Neural_Network, self).__init__()
        # parameters
        # TODO: parameters can be parameterized instead of declaring them here
        self.inputSize = x.size()[1]
        self.outputSize = y.size()[1]
        self.hiddenSize = 20
        
        # weights with + 1 for bias nodes
        self.W1 = torch.randn(self.inputSize + 1, self.hiddenSize)
        self.W2 = torch.randn(self.hiddenSize + 1, self.outputSize) 
        print(self.W1.size())
        
    def forward(self, X):
        #print(X.size())
        #print(self.W1.size())
        X_w_bias = torch.cat((X, torch.ones(x.size()[0], 1)), 1)
        #print("X_w_bias: " + str(X_w_bias.size()))
        self.z = torch.matmul(X_w_bias, self.W1) # 3 X 3 ".dot" does not broadcast in PyTorch
        self.z2 = self.sigmoid(self.z) # activation function
        z2_w_bias = torch.cat((self.z2, torch.ones(self.z2.size()[0], 1)), 1)
        #print("z2_w_bias: " + str(z2_w_bias.size()))

        self.z3 = torch.matmul(z2_w_bias, self.W2)
        o = self.sigmoid(self.z3) # final activation function            
        return o
        
    def sigmoid(self, s):
        return 1 / (1 + torch.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # derivative of sig to error
        self.z2_error = torch.matmul(self.o_delta, torch.t(self.W2))

        z2_w_bias = torch.cat((self.z2, torch.ones(self.z2.size()[0], 1)), 1)

        self.z2_delta = self.z2_error * self.sigmoidPrime(z2_w_bias)
        
        X_w_bias = torch.cat((X, torch.ones(x.size()[0], 1)), 1)
        
        self.z2_delta = self.z2_delta.narrow(1, 0, 20)

        #print(self.z2_delta.size(), self.o_delta.size())
        #print("self.z2_delta: " + str(self.z2_delta.size()))
        #print("torch.t(X).size(): " + str(torch.t(X).size()))
        #print("W1 size: " + str(self.W1.size()))
        self.W1 += torch.matmul(torch.t(X_w_bias), self.z2_delta)
        self.W2 += torch.matmul(torch.t(z2_w_bias), self.o_delta)
        
    def train(self, X, y):
        # forward + backward pass for training
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self, model):
        # we will use the PyTorch internal storage functions
        torch.save(model, "NN")
        # you can reload model with all the weights and so forth with:
        # torch.load("NN")
        
    def predict(self, X):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(X))
        foward_fn = self.forward(X)
        print ("Output: \n" + str(foward_fn))
        return forward_fn

In [58]:
NN = Neural_Network()
for i in range(1000):  # trains the NN 1,000 times
    print ("#" + str(i) + " Loss: " + str(torch.mean((y - NN(x)) ** 2).detach().item()))  # mean sum squared loss
    NN.train(x, y)
NN.saveWeights(NN)

torch.Size([14, 20])
#0 Loss: 0.45687001943588257
#1 Loss: 0.3333333432674408
#2 Loss: 0.3333333432674408
#3 Loss: 0.3333333432674408
#4 Loss: 0.3333333432674408
#5 Loss: 0.3333333432674408
#6 Loss: 0.3333333432674408
#7 Loss: 0.3333333432674408
#8 Loss: 0.3333333432674408
#9 Loss: 0.3333333432674408
#10 Loss: 0.3333333432674408
#11 Loss: 0.3333333432674408
#12 Loss: 0.3333333432674408
#13 Loss: 0.3333333432674408
#14 Loss: 0.3333333432674408
#15 Loss: 0.3333333432674408
#16 Loss: 0.3333333432674408
#17 Loss: 0.3333333432674408
#18 Loss: 0.3333333432674408
#19 Loss: 0.3333333432674408
#20 Loss: 0.3333333432674408
#21 Loss: 0.3333333432674408
#22 Loss: 0.3333333432674408
#23 Loss: 0.3333333432674408
#24 Loss: 0.3333333432674408
#25 Loss: 0.3333333432674408
#26 Loss: 0.3333333432674408
#27 Loss: 0.3333333432674408
#28 Loss: 0.3333333432674408
#29 Loss: 0.3333333432674408
#30 Loss: 0.3333333432674408
#31 Loss: 0.3333333432674408
#32 Loss: 0.3333333432674408
#33 Loss: 0.3333333432674408
#3

#402 Loss: 0.3333333432674408
#403 Loss: 0.3333333432674408
#404 Loss: 0.3333333432674408
#405 Loss: 0.3333333432674408
#406 Loss: 0.3333333432674408
#407 Loss: 0.3333333432674408
#408 Loss: 0.3333333432674408
#409 Loss: 0.3333333432674408
#410 Loss: 0.3333333432674408
#411 Loss: 0.3333333432674408
#412 Loss: 0.3333333432674408
#413 Loss: 0.3333333432674408
#414 Loss: 0.3333333432674408
#415 Loss: 0.3333333432674408
#416 Loss: 0.3333333432674408
#417 Loss: 0.3333333432674408
#418 Loss: 0.3333333432674408
#419 Loss: 0.3333333432674408
#420 Loss: 0.3333333432674408
#421 Loss: 0.3333333432674408
#422 Loss: 0.3333333432674408
#423 Loss: 0.3333333432674408
#424 Loss: 0.3333333432674408
#425 Loss: 0.3333333432674408
#426 Loss: 0.3333333432674408
#427 Loss: 0.3333333432674408
#428 Loss: 0.3333333432674408
#429 Loss: 0.3333333432674408
#430 Loss: 0.3333333432674408
#431 Loss: 0.3333333432674408
#432 Loss: 0.3333333432674408
#433 Loss: 0.3333333432674408
#434 Loss: 0.3333333432674408
#435 Loss:

#802 Loss: 0.3333333432674408
#803 Loss: 0.3333333432674408
#804 Loss: 0.3333333432674408
#805 Loss: 0.3333333432674408
#806 Loss: 0.3333333432674408
#807 Loss: 0.3333333432674408
#808 Loss: 0.3333333432674408
#809 Loss: 0.3333333432674408
#810 Loss: 0.3333333432674408
#811 Loss: 0.3333333432674408
#812 Loss: 0.3333333432674408
#813 Loss: 0.3333333432674408
#814 Loss: 0.3333333432674408
#815 Loss: 0.3333333432674408
#816 Loss: 0.3333333432674408
#817 Loss: 0.3333333432674408
#818 Loss: 0.3333333432674408
#819 Loss: 0.3333333432674408
#820 Loss: 0.3333333432674408
#821 Loss: 0.3333333432674408
#822 Loss: 0.3333333432674408
#823 Loss: 0.3333333432674408
#824 Loss: 0.3333333432674408
#825 Loss: 0.3333333432674408
#826 Loss: 0.3333333432674408
#827 Loss: 0.3333333432674408
#828 Loss: 0.3333333432674408
#829 Loss: 0.3333333432674408
#830 Loss: 0.3333333432674408
#831 Loss: 0.3333333432674408
#832 Loss: 0.3333333432674408
#833 Loss: 0.3333333432674408
#834 Loss: 0.3333333432674408
#835 Loss:

In [57]:
predictions = NN.forward(x)
print("------")
#print(predictions)
#print(type(predictions))
correct = 0
for i in range(len(predictions)):
    #print("prediction: " + str(predictions[i]))
    #print("actual: " + str(y[i]))
    
    pred = predictions[i].tolist()
    actual = y[i].tolist()
    if pred.index(max(pred)) == actual.index(max(actual)):
        correct += 1

print("accuracy: " + str(correct / len(predictions)))
    

------
accuracy: 0.4011299435028249


In [11]:
x = x.float()
y = y.float()
print(x.type())
print(y.type())

torch.FloatTensor
torch.FloatTensor


In [23]:
x

tensor([[ 0.7802,  0.7748,  0.9380,  ...,  0.7896,  0.7761,  0.9056],
        [-0.3862, -0.1862, -0.3276,  ...,  0.4759, -0.1069,  0.4138],
        [ 0.3251,  0.6533,  0.5480,  ...,  0.3994,  0.4675,  0.6966],
        ...,
        [ 0.2281,  0.2047,  0.0058,  ..., -0.3099, -0.2982, -0.2865],
        [ 0.7000,  0.5850,  0.7250,  ..., -0.2200, -0.1900, -0.2000],
        [ 0.2500,  0.4107,  0.7619,  ..., -0.0060,  0.0000, -0.3333]])

In [ ]:
# need to add bias values to input and hidden layer!!!


In [56]:
NN.predict(x)

Predicted data based on trained weights: 
Input (scaled): 
tensor([[ 0.7802, -0.3862,  0.3251,  ...,  0.2281,  0.7000,  0.2500],
        [ 0.7748, -0.1862,  0.6533,  ...,  0.2047,  0.5850,  0.4107],
        [ 0.9380, -0.3276,  0.5480,  ...,  0.0058,  0.7250,  0.7619],
        ...,
        [ 0.7896,  0.4759,  0.3994,  ..., -0.3099, -0.2200, -0.0060],
        [ 0.7761, -0.1069,  0.4675,  ..., -0.2982, -0.1900,  0.0000],
        [ 0.9056,  0.4138,  0.6966,  ..., -0.2865, -0.2000, -0.3333]])
Output: 
tensor([[7.9406e-17, 2.3666e-07, 3.7494e-11],
        [5.1035e-16, 1.3248e-07, 4.3855e-11],
        [8.4645e-14, 1.6225e-07, 3.9584e-08],
        [2.6061e-17, 1.2229e-07, 3.9222e-09],
        [9.8707e-15, 2.7804e-07, 2.2305e-09],
        [6.8918e-15, 4.7084e-07, 1.3709e-09],
        [9.3432e-15, 3.2216e-07, 5.8709e-08],
        [1.7848e-16, 2.2602e-07, 4.1539e-11],
        [6.3615e-16, 2.4281e-07, 4.1475e-10],
        [6.3757e-16, 9.5969e-08, 2.5043e-11],
        [1.3418e-14, 4.1473e-07, 7.555

In [59]:
df.to_csv("/home/dom/Documents/MPhys/TheGrandTour/wine_data.csv", index=False)

In [68]:
x.size()

torch.Size([177, 13])

In [91]:
torch.cat((x, torch.ones(x.size()[0], 1)), 1).size()

torch.Size([177, 14])

In [85]:
x.size()[0]

177

In [33]:
test = torch.randn(20, 20)

In [35]:
test.size()

torch.Size([20, 20])

In [37]:
test.narrow(1, 0, 19).size()

torch.Size([20, 19])