In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/home/dom/Documents/MPhys/TheGrandTour/wine_data.txt", sep="\t");
data = np.array(df);
data = np.delete(data, 0, 0)
data = data.astype(float)
data = np.swapaxes(data,0,1)


classification = data[13]
data = np.delete(data, 13, axis=0)
# Normalizes the data        
for i in range(0, np.shape(data)[0]):
    data[i,:] = (data[i,:] / np.ndarray.max(data[i,:])) * 2 - 1

In [7]:
targetData = np.zeros((len(data[0]), 3))
for counter, i in enumerate(classification):
    targetData[counter][int(i-1)] = 1


In [12]:
x = torch.from_numpy(data)
y = torch.from_numpy(targetData)
x.transpose_(0, 1)


tensor([[ 0.7802, -0.3862,  0.3251,  ...,  0.2281,  0.7000,  0.2500],
        [ 0.7748, -0.1862,  0.6533,  ...,  0.2047,  0.5850,  0.4107],
        [ 0.9380, -0.3276,  0.5480,  ...,  0.0058,  0.7250,  0.7619],
        ...,
        [ 0.7896,  0.4759,  0.3994,  ..., -0.3099, -0.2200, -0.0060],
        [ 0.7761, -0.1069,  0.4675,  ..., -0.2982, -0.1900,  0.0000],
        [ 0.9056,  0.4138,  0.6966,  ..., -0.2865, -0.2000, -0.3333]],
       dtype=torch.float64)

In [13]:
print(x.size())
print(y.size())

torch.Size([177, 13])
torch.Size([177, 3])


In [ ]:
class Neural_Network(nn.Module):
    def __init__(self, x, y, hidden_nodes=10):
        self.hidden_nodes = hidden_nodes # number of nodes in each layer (not inc. bias)
        self.x = x # input data 
        self.y = y # target data
        self.w1 = torch.randn(self.num_nodes, x.size()[1] + 1)
        self.w2 = torch.randn(y.size()[1], self.num_nodes + 1)

               
    def sigmoid(self, x):
        return 1 / (1 + torch.exp(-x))
        
    def sigmoidPrime(self, x)
        return x * (1 - x)
    
    def forward(self, x):
        self.z1 = torch.matmul(self.w1, x)
        self.a1 = self.sigmoid(self.z)
        self.z2 = torch.matmul(self.w2, )
        
    
    
    
    
    
    
    
    
    
    
    
    

In [8]:
import torch
x = torch.randn(1, 2, 1)
y = torch.randn(3, 4, 1)
z = torch.randn(5, 6, 1)


In [10]:
w = torch.cat((x, y, z), dim=2)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 1 and 3 in dimension 0 at /pytorch/aten/src/TH/generic/THTensorMath.cpp:3616

In [9]:
print(x)
print("--------")
print(y)
print("--------")
print(z)
print("--------")

tensor([[[ 0.5030],
         [-0.9748]]])
--------
tensor([[[-0.4020],
         [ 0.4924],
         [-0.3642],
         [-0.4512]],

        [[-0.9332],
         [-0.5699],
         [-0.8318],
         [-0.5172]],

        [[ 0.1323],
         [ 0.6076],
         [-0.0779],
         [-1.4012]]])
--------
tensor([[[ 0.4226],
         [-0.7153],
         [-1.0910],
         [-0.7419],
         [ 0.7639],
         [ 1.0207]],

        [[ 1.5074],
         [ 0.8015],
         [-0.2620],
         [-0.0466],
         [-1.6500],
         [-0.2469]],

        [[ 1.4133],
         [-0.0205],
         [ 0.2990],
         [ 0.5569],
         [ 0.1971],
         [-1.6539]],

        [[-0.2641],
         [ 1.3734],
         [ 0.5504],
         [-0.7450],
         [ 0.7423],
         [-0.0800]],

        [[-1.2155],
         [-0.0283],
         [-0.2870],
         [ 1.2559],
         [-0.7488],
         [-0.0230]]])
--------


In [5]:
z

tensor([[ 0.3302, -0.2194,  0.0752,  1.9084, -0.3012, -0.9315],
        [-0.8804,  0.1797, -1.1256, -0.5432, -0.3351, -0.5285],
        [ 1.0745,  0.3769,  0.2922, -1.0382, -1.1002,  0.4179],
        [ 0.9122,  0.1097, -0.4777,  0.1887, -0.4481,  0.0565],
        [-0.7248,  0.6019,  0.9330, -1.2040, -0.1286,  1.2716]])