In [12]:
import numpy as np
import pandas as pd
import time
from sklearn.svm import SVC,LinearSVC
from sklearn.multiclass import OneVsRestClassifier

#Sphere
nPoints = 5000
data = np.zeros((4,nPoints))
b = 2*np.pi*np.random.uniform(0,1,2)
for i in range(0,nPoints):
    a = b*i
    data[1,i] = np.sin(a[0])*np.cos(a[1])
    data[2,i] = np.sin(a[0])*np.sin(a[1])
    data[3,i] = np.cos(a[0])
    
def LorentzBoost(phi, i):
    """
    Inputs:
    i = first indicie of rotating plane
    j = second indicie of rotating plane
    d = dimensions of data
    theta = dxd array of angle of rotation of rotating plane

    Outputs a rotating matrix to rotate plane of ixj plane by theta_ij
    """
    R = np.identity(4)
    R[0,0] = np.cosh(phi)
    R[0,i] = -np.sinh(phi)
    R[i,0] = -np.sinh(phi)
    R[i,i] = np.cosh(phi)
    return R

def AccelerateTour(data, nSteps):
    """
    Inputs:
    data = array of data points, dimensions x npoints
    Outputs a 3D array number of points x t x dimensions, where t
    the time step at that point in the tour
    """

    d = np.shape(data)[0] #dimensions of data
    nPoints = np.shape(data)[1] #number of data points
    tData = np.zeros((nSteps,d,nPoints)) #initialise 3d matrix to store stransforemd data at each timestep
    beta = 0
    i = 3

    
    for t in range(0, nSteps): 
        
        beta = t/nSteps
        
        phi = np.arctanh(beta)
        b = LorentzBoost(phi,i)
        a = np.matmul(b, data)
        print(a[:,1])
        tData[t,:,:] = a
        
        
    return tData

tData = AccelerateTour(data,1000)

[ 0.         -0.61012686 -0.63678173  0.47143849]
[-4.71438722e-04 -6.10126861e-01 -6.36781727e-01  4.71438722e-01]
[-0.00094288 -0.61012686 -0.63678173  0.47143943]
[-0.00141432 -0.61012686 -0.63678173  0.47144061]
[-0.00188577 -0.61012686 -0.63678173  0.47144226]
[-0.00235722 -0.61012686 -0.63678173  0.47144438]
[-0.00282868 -0.61012686 -0.63678173  0.47144697]
[-0.00330015 -0.61012686 -0.63678173  0.47145004]
[-0.00377163 -0.61012686 -0.63678173  0.47145357]
[-0.00424312 -0.61012686 -0.63678173  0.47145758]
[-0.00471462 -0.61012686 -0.63678173  0.47146206]
[-0.00518614 -0.61012686 -0.63678173  0.47146701]
[-0.00565767 -0.61012686 -0.63678173  0.47147243]
[-0.00612922 -0.61012686 -0.63678173  0.47147833]
[-0.00660079 -0.61012686 -0.63678173  0.47148469]
[-0.00707237 -0.61012686 -0.63678173  0.47149153]
[-0.00754398 -0.61012686 -0.63678173  0.47149884]
[-0.00801561 -0.61012686 -0.63678173  0.47150662]
[-0.00848727 -0.61012686 -0.63678173  0.47151488]
[-0.00895895 -0.61012686 -0.636781

[-0.15371864 -0.61012686 -0.63678173  0.49586658]
[-0.15426751 -0.61012686 -0.63678173  0.49603701]
[-0.15481694 -0.61012686 -0.63678173  0.49620815]
[-0.15536695 -0.61012686 -0.63678173  0.49638003]
[-0.15591753 -0.61012686 -0.63678173  0.49655264]
[-0.15646868 -0.61012686 -0.63678173  0.49672598]
[-0.15702041 -0.61012686 -0.63678173  0.49690005]
[-0.15757273 -0.61012686 -0.63678173  0.49707485]
[-0.15812563 -0.61012686 -0.63678173  0.4972504 ]
[-0.15867911 -0.61012686 -0.63678173  0.49742668]
[-0.15923319 -0.61012686 -0.63678173  0.49760371]
[-0.15978786 -0.61012686 -0.63678173  0.49778148]
[-0.16034312 -0.61012686 -0.63678173  0.49796   ]
[-0.16089898 -0.61012686 -0.63678173  0.49813927]
[-0.16145545 -0.61012686 -0.63678173  0.49831928]
[-0.16201252 -0.61012686 -0.63678173  0.49850005]
[-0.16257019 -0.61012686 -0.63678173  0.49868158]
[-0.16312848 -0.61012686 -0.63678173  0.49886386]
[-0.16368738 -0.61012686 -0.63678173  0.4990469 ]
[-0.1642469  -0.61012686 -0.63678173  0.4992307 ]


[-0.30089028 -0.61012686 -0.63678173  0.55927561]
[-0.30167827 -0.61012686 -0.63678173  0.55969994]
[-0.30246806 -0.61012686 -0.63678173  0.56012603]
[-0.30325965 -0.61012686 -0.63678173  0.56055389]
[-0.30405307 -0.61012686 -0.63678173  0.56098353]
[-0.30484832 -0.61012686 -0.63678173  0.56141495]
[-0.3056454  -0.61012686 -0.63678173  0.56184816]
[-0.30644433 -0.61012686 -0.63678173  0.56228318]
[-0.30724513 -0.61012686 -0.63678173  0.56272001]
[-0.30804779 -0.61012686 -0.63678173  0.56315867]
[-0.30885234 -0.61012686 -0.63678173  0.56359916]
[-0.30965878 -0.61012686 -0.63678173  0.56404149]
[-0.31046712 -0.61012686 -0.63678173  0.56448568]
[-0.31127738 -0.61012686 -0.63678173  0.56493172]
[-0.31208956 -0.61012686 -0.63678173  0.56537964]
[-0.31290368 -0.61012686 -0.63678173  0.56582945]
[-0.31371975 -0.61012686 -0.63678173  0.56628114]
[-0.31453778 -0.61012686 -0.63678173  0.56673474]
[-0.31535778 -0.61012686 -0.63678173  0.56719024]
[-0.31617976 -0.61012686 -0.63678173  0.56764768]


[-0.49337917 -0.61012686 -0.63678173  0.68240549]
[-0.49481223 -0.61012686 -0.63678173  0.68344231]
[-0.49625186 -0.61012686 -0.63678173  0.68448532]
[-0.49769809 -0.61012686 -0.63678173  0.68553456]
[-0.49915101 -0.61012686 -0.63678173  0.68659011]
[-0.50061066 -0.61012686 -0.63678173  0.687652  ]
[-0.50207711 -0.61012686 -0.63678173  0.68872031]
[-0.50355042 -0.61012686 -0.63678173  0.68979509]
[-0.50503065 -0.61012686 -0.63678173  0.6908764 ]
[-0.50651787 -0.61012686 -0.63678173  0.69196431]
[-0.50801215 -0.61012686 -0.63678173  0.69305886]
[-0.50951354 -0.61012686 -0.63678173  0.69416013]
[-0.51102212 -0.61012686 -0.63678173  0.69526819]
[-0.51253795 -0.61012686 -0.63678173  0.69638308]
[-0.5140611  -0.61012686 -0.63678173  0.69750488]
[-0.51559164 -0.61012686 -0.63678173  0.69863365]
[-0.51712964 -0.61012686 -0.63678173  0.69976947]
[-0.51867517 -0.61012686 -0.63678173  0.70091239]
[-0.5202283  -0.61012686 -0.63678173  0.70206248]
[-0.52178911 -0.61012686 -0.63678173  0.70321982]


[-0.97339866 -0.61012686 -0.63678173  1.08155406]
[-0.97913183 -0.61012686 -0.63678173  1.08671679]
[-0.98494794 -0.61012686 -0.63678173  1.09196002]
[-0.99084911 -0.61012686 -0.63678173  1.09728583]
[-0.99683752 -0.61012686 -0.63678173  1.10269637]
[-1.00291545 -0.61012686 -0.63678173  1.10819386]
[-1.00908525 -0.61012686 -0.63678173  1.11378062]
[-1.01534936 -0.61012686 -0.63678173  1.11945905]
[-1.02171033 -0.61012686 -0.63678173  1.12523164]
[-1.02817078 -0.61012686 -0.63678173  1.13110097]
[-1.03473345 -0.61012686 -0.63678173  1.13706972]
[-1.04140118 -0.61012686 -0.63678173  1.1431407 ]
[-1.04817692 -0.61012686 -0.63678173  1.1493168 ]
[-1.05506375 -0.61012686 -0.63678173  1.15560104]
[-1.06206485 -0.61012686 -0.63678173  1.16199656]
[-1.06918357 -0.61012686 -0.63678173  1.16850663]
[-1.07642335 -0.61012686 -0.63678173  1.17513467]
[-1.08378782 -0.61012686 -0.63678173  1.18188421]
[-1.09128073 -0.61012686 -0.63678173  1.18875897]
[-1.09890601 -0.61012686 -0.63678173  1.1957628 ]


In [13]:
from pyqtgraph.Qt import QtGui, QtCore
import pandas as pd
import pyqtgraph as pg
import time

if __name__ == '__main__':
    
    app = 0
    app = QtGui.QApplication([])
    mw = QtGui.QMainWindow()
    mw.resize(800,800)
    view = pg.GraphicsLayoutWidget()  ## GraphicsView with GraphicsLayout inserted by default
    mw.setCentralWidget(view)
    mw.show()
    mw.setWindowTitle('pyqtgraph example: ScatterPlot')

    ## create four areas to add plots
    w1 = view.addPlot()


    ## There are a few different ways we can draw scatter plots; each is optimized for different types of data:


    ## 1) All spots identical and transform-invariant (top-left plot). 
    ## In this case we can get a huge performance boost by pre-rendering the spot 
    ## image and just drawing that image repeatedly.
    nPoints = np.shape(tData)[2]
    s1 = pg.ScatterPlotItem(size=10, pen=pg.mkPen(None), brush=pg.mkBrush(0, 227, 17,120))
    pos = np.zeros((2,nPoints))
    j = 0
    pos[0,:] = tData[j,1,:]
    pos[1,:] = tData[j,3,:]
    spots = [{'pos': pos[:,i], 'data': 1} for i in range(nPoints)]
    s1.addPoints(spots)
    w1.addItem(s1)

    def update():
        global j
        j += 1
        if j > np.shape(tData)[0]-1:
            j = 0
        pos[0,:] = tData[j,1,:]
        pos[1,:] = tData[j,3,:]
        spots = [{'pos': pos[:,i], 'data': 1} for i in range(nPoints)]
        s1.setData(spots)

    t = QtCore.QTimer()
    t.timeout.connect(update)
    t.start(10)

## 2) Spots are transform-invariant, but not identical (top-right plot). 
## In this case, drawing is almsot as fast as 1), but there is more startup 
## overhead and memory usage since each spot generates its own pre-rendered 
## image.



## Start Qt event loop unless running in interactive mode.
    sys.exit(app.exec_())



SystemExit: 0

/Users/karanmukhi/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
